const labels={beranda:'Beranda',peta:'Peta sensor',analitik:'Analitik AI',audit:'Audit ESG',peringatan:'Peringatan',aerobot:'Tanya AERO-BOT'};
function showView(name){const target=document.getElementById('view-'+name);if(!target)return;document.querySelectorAll('.view').forEach(el=>el.classList.toggle('active',el===target));document.querySelectorAll('.nav-item').forEach(el=>el.classList.toggle('active',el.dataset.view===name));document.getElementById('breadcrumbCurrent').textContent=labels[name]||name;document.getElementById('sidebar').classList.remove('open');document.getElementById('menuButton').setAttribute('aria-expanded','false');history.replaceState(null,'','#'+name);window.scrollTo({top:0,behavior:'auto'});}
document.querySelectorAll('[data-view]').forEach(el=>el.addEventListener('click',()=>showView(el.dataset.view)));
document.getElementById('menuButton').addEventListener('click',()=>{const nav=document.getElementById('sidebar');nav.classList.toggle('open');document.getElementById('menuButton').setAttribute('aria-expanded',nav.classList.contains('open'));});
window.addEventListener('keydown',event=>{if(event.key==='Escape'){document.getElementById('sidebar').classList.remove('open');document.getElementById('menuButton').setAttribute('aria-expanded','false');}});
showView((location.hash||'#beranda').slice(1));
document.querySelector('.brand').addEventListener('click',event=>{event.preventDefault();showView('beranda');});
window.addEventListener('hashchange',()=>showView((location.hash||'#beranda').slice(1)));
document.querySelector('.page-area').addEventListener('click',event=>{if(event.target.closest('#menuButton'))return;document.getElementById('sidebar').classList.remove('open');document.getElementById('menuButton').setAttribute('aria-expanded','false');});

const nodes=[
  {name:'Cerme',id:'AS-CRM-01',aqi:38,pm:'12,1',co2:552,tvoc:74,temp:'29,8',status:'baik'},
  {name:'Gresik Kota',id:'AS-GRK-02',aqi:44,pm:'15,2',co2:590,tvoc:89,temp:'30,2',status:'baik'},
  {name:'Manyar',id:'AS-MYR-03',aqi:65,pm:'25,8',co2:688,tvoc:221,temp:'31,1',status:'perhatian'},
  {name:'Bungah',id:'AS-BGH-04',aqi:41,pm:'13,6',co2:568,tvoc:81,temp:'29,4',status:'baik'},
  {name:'Sidayu',id:'AS-SDY-05',aqi:84,pm:'32,4',co2:714,tvoc:168,temp:'31,5',status:'perhatian'},
  {name:'Driyorejo',id:'AS-DRY-06',aqi:48,pm:'16,8',co2:602,tvoc:92,temp:'30,7',status:'baik'},
  {name:'Kebomas',id:'AS-KBM-07',aqi:43,pm:'14,7',co2:584,tvoc:86,temp:'30,0',status:'baik'},
  {name:'Menganti',id:'AS-MGT-08',aqi:46,pm:'15,9',co2:598,tvoc:90,temp:'30,3',status:'baik'},
  {name:'Ujungpangkah',id:'AS-UJP-09',aqi:36,pm:'11,8',co2:540,tvoc:71,temp:'29,6',status:'baik'},
  {name:'Wringinanom',id:'AS-WRN-10',aqi:47,pm:'16,3',co2:606,tvoc:95,temp:'30,4',status:'baik'}
];
let nodeFilter='semua';
function renderNodes(){const selected=nodeFilter==='semua'?nodes:nodes.filter(node=>node.status===nodeFilter);document.getElementById('visibleCount').textContent=`${selected.length} node ditampilkan`;document.getElementById('nodeTable').innerHTML=selected.map(node=>`<tr><td><button class="table-row-select" data-node="${node.name}">${node.name}</button></td><td>${node.id}</td><td><strong>${node.aqi}</strong></td><td>${node.pm} µg/m³</td><td><span class="table-status ${node.status==='baik'?'good':'warn'}">${node.status==='baik'?'Baik':'Perlu perhatian'}</span></td><td>09.41 WIB</td></tr>`).join('');document.querySelectorAll('#nodeTable [data-node]').forEach(button=>button.addEventListener('click',()=>selectNode(button.dataset.node)));document.querySelectorAll('.expanded-map .map-node').forEach(marker=>{marker.hidden=nodeFilter!=='semua'&&marker.dataset.status!==nodeFilter;});}
function selectNode(name){const node=nodes.find(item=>item.name===name);if(!node)return;document.getElementById('nodeName').textContent=node.name;document.getElementById('nodeId').textContent=`${node.id} • Aktif`;document.getElementById('nodeAqi').innerHTML=`${node.aqi} <small>AQI</small>`;document.getElementById('nodePm').textContent=`${node.pm} µg/m³`;document.getElementById('nodeCo2').textContent=`${node.co2} ppm`;document.getElementById('nodeTvoc').textContent=`${node.tvoc} ppb`;document.getElementById('nodeTemp').textContent=`${node.temp}°C`;const chip=document.getElementById('nodeStatus');chip.textContent=node.status==='baik'?'Baik':'Perlu perhatian';chip.className=`status-chip ${node.status==='baik'?'good':'warn'}`;document.querySelectorAll('.expanded-map .map-node').forEach(marker=>marker.classList.toggle('selected',marker.dataset.node===name));}
document.querySelectorAll('[data-node-filter]').forEach(button=>button.addEventListener('click',()=>{nodeFilter=button.dataset.nodeFilter;document.querySelectorAll('[data-node-filter]').forEach(el=>el.classList.toggle('active',el===button));renderNodes();}));
document.querySelectorAll('.expanded-map .map-node').forEach(button=>button.addEventListener('click',()=>selectNode(button.dataset.node)));
document.querySelectorAll('#homeMap .map-node').forEach((button,index)=>button.addEventListener('click',()=>{showView('peta');selectNode(['Cerme','Gresik Kota','Manyar','Bungah','Sidayu','Driyorejo'][index]);}));
renderNodes();selectNode('Gresik Kota');

const chartSets={
  '24':{raw:'0,164 44,150 88,164 132,124 176,153 220,138 264,92 308,120 352,70 396,104 440,85 484,123 528,95 572,143 616,133 660,151',estimate:'0,157 44,152 88,145 132,139 176,143 220,128 264,118 308,111 352,102 396,98 440,102 484,114 528,120 572,128 616,139 660,146',labels:['00.00','04.00','08.00','12.00','16.00','20.00','24.00']},
  '7':{raw:'0,151 44,130 88,141 132,85 176,113 220,115 264,98 308,128 352,75 396,93 440,108 484,69 528,84 572,126 616,112 660,90',estimate:'0,145 44,138 88,129 132,119 176,118 220,121 264,113 308,109 352,100 396,97 440,99 484,88 528,93 572,100 616,105 660,98',labels:['Sen','Sel','Rab','Kam','Jum','Sab','Min']}
};
document.querySelectorAll('[data-range]').forEach(button=>button.addEventListener('click',()=>{const set=chartSets[button.dataset.range];document.querySelectorAll('[data-range]').forEach(el=>el.classList.toggle('active',el===button));document.querySelector('.raw-line').setAttribute('points',set.raw);document.querySelector('.estimate-line').setAttribute('points',set.estimate);document.querySelectorAll('.chart-x span').forEach((el,index)=>el.textContent=set.labels[index]);document.getElementById('aiChart').setAttribute('aria-label',`Grafik pembacaan mentah dan estimasi AI PM2.5 selama ${button.dataset.range==='24'?'24 jam':'7 hari'}`);}));

const reportRows=[['Waktu','Lokasi','Parameter','Mentah','Estimasi','Status'],['30 Sep 2026 09:25','Sidayu','PM2.5','37,8 µg/m³','32,4 µg/m³','Ditinjau'],['30 Sep 2026 08:50','Manyar','TVOC','235 ppb','221 ppb','Ditinjau'],['30 Sep 2026 08:30','Gresik Kota','PM2.5','16,5 µg/m³','15,2 µg/m³','Tercatat'],['30 Sep 2026 08:15','Cerme','PM2.5','13,4 µg/m³','12,1 µg/m³','Tercatat']];
function download(name,mime,content){const blob=new Blob([content],{type:mime});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=name;document.body.append(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function csvCell(value){return `"${String(value).replaceAll('"','""')}"`;}
document.getElementById('exportCsv').addEventListener('click',()=>{const header=[['AEROSENSE — DATA SIMULASI'],['Periode',document.getElementById('reportPeriod').value],['Wilayah',document.getElementById('reportRegion').value],[]];download('AEROSENSE_Laporan_Contoh.csv','text/csv;charset=utf-8','\ufeff'+header.concat(reportRows).map(row=>row.map(csvCell).join(',')).join('\r\n'));showToast('CSV berhasil diunduh.');});
function xmlEscape(value){return String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');}
document.getElementById('exportExcel').addEventListener('click',()=>{const rows=[['AEROSENSE — DATA SIMULASI'],['Periode',document.getElementById('reportPeriod').value],['Wilayah',document.getElementById('reportRegion').value],[],...reportRows];const xml=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="Audit ESG"><Table>${rows.map(row=>`<Row>${row.map(cell=>`<Cell><Data ss:Type="String">${xmlEscape(cell)}</Data></Cell>`).join('')}</Row>`).join('')}</Table></Worksheet></Workbook>`;download('AEROSENSE_Laporan_Contoh.xml','application/vnd.ms-excel;charset=utf-8',xml);showToast('File yang dapat dibuka di Excel berhasil diunduh.');});
document.getElementById('exportPdf').addEventListener('click',()=>{const win=window.open('','_blank');if(!win){showToast('Izinkan jendela baru untuk menyimpan PDF.');return;}const period=xmlEscape(document.getElementById('reportPeriod').value),region=xmlEscape(document.getElementById('reportRegion').value);win.document.write(`<!doctype html><html lang="id"><head><meta charset="utf-8"><title>Laporan contoh AEROSENSE</title><style>body{font-family:Arial,sans-serif;color:#153052;padding:36px;max-width:900px;margin:auto}h1{color:#076cf0;font-size:26px}p{line-height:1.5}.note{background:#eaf5ff;padding:12px;border-radius:8px}table{border-collapse:collapse;width:100%;margin-top:24px}th,td{text-align:left;border-bottom:1px solid #dce7f3;padding:10px;font-size:12px}th{background:#eff7ff}small{color:#6f839a}</style></head><body><h1>AEROSENSE™ — Laporan ESG</h1><p>Periode: <b>${period}</b><br>Wilayah: <b>${region}</b></p><p class="note"><b>Data simulasi.</b> Dokumen ini dibuat untuk pratinjau antarmuka dan tidak berlaku sebagai bukti audit resmi. Skor kepatuhan contoh: 92/100. Estimasi jejak karbon memerlukan data aktivitas dan faktor emisi tervalidasi.</p><h2>Cuplikan log pemantauan</h2><table><thead><tr>${reportRows[0].map(cell=>`<th>${xmlEscape(cell)}</th>`).join('')}</tr></thead><tbody>${reportRows.slice(1).map(row=>`<tr>${row.map(cell=>`<td>${xmlEscape(cell)}</td>`).join('')}</tr>`).join('')}</tbody></table><p><small>AEROSENSE • Simulasi antarmuka • 30 September 2026</small></p></body></html>`);win.document.close();setTimeout(()=>{win.focus();win.print();},350);});

document.querySelectorAll('[data-ack]').forEach(button=>button.addEventListener('click',()=>{const id=button.dataset.ack;document.getElementById('alertState'+id).textContent='Sudah dibaca';button.textContent='Sudah dibaca';button.disabled=true;showToast('Peringatan ditandai sudah dibaca pada sesi ini.');}));

const chatMessages=document.getElementById('chatMessages');
function replyFor(question){const text=question.toLowerCase();if(text.includes('aqi'))return 'AQI adalah indeks yang merangkum kondisi kualitas udara. AQI kawasan tercatat 52, kategori sedang. Artinya, sebagian besar orang dapat beraktivitas biasa, tetapi kelompok sensitif sebaiknya memantau kondisi di lokasi terdekat.';if(text.includes('pm2.5')||text.includes('debu'))return 'PM2.5 adalah partikel halus di udara. Jika nilainya meningkat, kurangi aktivitas luar ruang yang lama, gunakan masker yang sesuai saat perlu keluar, dan perhatikan informasi dari layanan kesehatan setempat.';if(text.includes('manyar'))return 'Node Manyar memiliki AQI 65 dan TVOC 221 ppb. Statusnya sedang dipantau. Cek peringatan terbaru sebelum berkegiatan di sekitar lokasi.';if(text.includes('sidayu'))return 'Node Sidayu memiliki AQI 84 dan PM2.5 32,4 µg/m³. Batasi aktivitas luar ruang yang lama, terutama bagi anak-anak dan orang yang sensitif terhadap polusi.';if(text.includes('co2')||text.includes('karbon'))return 'eCO₂ adalah perkiraan konsentrasi setara CO₂ dari sensor gas. Nilai ini tidak sama dengan jumlah emisi karbon perusahaan. Audit jejak karbon memerlukan metode dan data tambahan.';if(text.includes('hari ini')||text.includes('kondisi')||text.includes('udara'))return 'Rata-rata AQI kawasan berada di angka 52 (sedang). Delapan node berkondisi baik dan dua titik, Manyar serta Sidayu, perlu perhatian. Pilih Peta sensor untuk melihat rincian tiap lokasi.';return 'Saya bisa membantu menjelaskan AQI, PM2.5, eCO₂, TVOC, status node, dan langkah umum saat udara memburuk. Coba tanyakan tentang kondisi hari ini, Manyar, atau Sidayu.';}
function addMessage(text,who){const message=document.createElement('div');message.className=`chat-message ${who}`;if(who==='bot'){const avatar=document.createElement('span');avatar.className='message-avatar mascot-avatar';avatar.innerHTML='<img src="assets/aerobot.svg" alt="" width="112" height="112">';message.append(avatar);}const content=document.createElement('div');content.className='message-content';const bubble=document.createElement('p');bubble.textContent=text;content.append(bubble);message.append(content);chatMessages.append(message);chatMessages.scrollTop=chatMessages.scrollHeight;}
function sendChat(text){const clean=text.trim();if(!clean)return;addMessage(clean,'user');document.getElementById('chatInput').value='';document.getElementById('promptSuggestions').hidden=true;setTimeout(()=>addMessage(replyFor(clean),'bot'),450);}
document.getElementById('chatForm').addEventListener('submit',event=>{event.preventDefault();sendChat(document.getElementById('chatInput').value);});
document.querySelectorAll('[data-prompt]').forEach(button=>button.addEventListener('click',()=>sendChat(button.dataset.prompt)));
function showToast(text){let toast=document.getElementById('appToast');if(!toast){toast=document.createElement('div');toast.id='appToast';toast.className='app-toast';toast.setAttribute('role','status');document.body.append(toast);}toast.textContent=text;toast.classList.add('visible');clearTimeout(showToast.timeout);showToast.timeout=setTimeout(()=>toast.classList.remove('visible'),3000);}

const sampleRecommendations=[
  'Kalau keluar rumah hari ini, cek kondisi udara di lokasi terdekat. Bawa masker sebagai langkah siap siaga.',
  'Semangat menjalani hari! Mulai dengan melihat kualitas udara sebelum berangkat, lalu pilih aktivitas yang paling nyaman.',
  'Jaga napas, jaga semangat. Saat udara terasa kurang nyaman, beri diri Anda waktu untuk beristirahat di dalam ruangan.',
  'Langkah kecil juga berarti: ingatkan keluarga untuk memeriksa kondisi udara sebelum beraktivitas di luar.',
  'Udara yang lebih sehat dimulai dari kebiasaan bersama. Terus pantau, saling peduli, dan tetap semangat!'
];
let recommendationIndex=0;
function showRecommendation(text){document.getElementById('recommendText').textContent=text;}
document.getElementById('recommendNext').addEventListener('click',()=>{
  const offset=1+Math.floor(Math.random()*(sampleRecommendations.length-1));
  recommendationIndex=(recommendationIndex+offset)%sampleRecommendations.length;
  showRecommendation(sampleRecommendations[recommendationIndex]);
});
// A future server-side Gemini integration can replace this sample copy via this UI hook.
window.AeroSenseUI={showRecommendation};
